LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_C_INCLUDES := system/core/init
LOCAL_CFLAGS := -Wall -DANDROID_TARGET=\"$(TARGET_BOARD_PLATFORM)\"
LOCAL_SRC_FILES := init_sd4xx.cpp
ifneq ($(TARGET_LIBINIT_SD4XX_DEFINES_FILE),)
  LOCAL_SRC_FILES += ../../../../$(TARGET_LIBINIT_SD4XX_DEFINES_FILE)
endif
LOCAL_MODULE := libinit_sd4xx

include $(BUILD_STATIC_LIBRARY)